
export interface JobOffer {
    id: string;
  title: string;
  description: string;
  responsibilities: string;
  requirements: string;
  idealCandidate: string;
  categories: string[];
  opType: 'inPerson' | string; 
  startDate: string; 
  endDate: string; 
  deadline: string; 
  location: string[];
  requiredSkills: string[];
  whenAndWhere: string;
  orgID: string;
  datePosted: string; 
  status: 'open' | string; 
  applicantsCount: number;
  viewsCount: number;
  orgName: string;
  logoUrl: string; 
  isBookmarked: boolean;
  isRolling: boolean;
  createdAt: string; 
  updatedAt: string; 
  orgPrimaryPhone: string;
  orgEmail: string;
  average_rating: number;
  total_reviews: number;
};